# Generated by Django 5.2 on 2025-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
